### ISSUE TITLE
Improving

### ISSUE THREAD

**Issue by su8** [DmitryMyadzelets/svelte-server-client-rendering#1]
https://github.com/DmitryMyadzelets/svelte-server-client-rendering/blob/b4301d9a5ce9fde27aa5247406ab261290a2c0d9/public/client.js#L14 instanceof Function

**Comment by DmitryMyadzelets** [comment]
Thanks for looking around here.
This file is automatically generated during complication. By the Svelte.
I've improved the README so it's more clear now, I hope :)

**Comment by DmitryMyadzelets** [comment]
P.S. I've googled around and found that:

> `instanceOf` wouldn't work on functions defined in other windows, I believe. Their `Function` is different than ` window.Function`

From a [discussion at SO](https://stackoverflow.com/questions/899574/what-is-the-difference-between-typeof-and-instanceof-and-when-should-one-be-used). Since the Svelte's main purpose is to create a code for browsers it's logical to use the safest approach.
